# Generated by Django 4.2.1 on 2023-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
