# Generated by Django 4.2 on 2023-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliodoc_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodoc',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
